// Neon Survivor - Player runtime state.
// Mirrors every card-derived stat from the original HTML playerStats blob.

export interface PlayerRuntime {
  hp: number;
  maxHp: number;
  shield: number;
  maxShield: number;
  // Weapon
  currentWeapon: number;
  weaponId: string;
  ammo: number;
  maxAmmo: number;
  fireRate: number;
  baseDamage: number;
  reloadTime: number;
  pellets: number;
  spread: number;
  fireCooldown: number;
  reloading: boolean;
  reloadT: number;
  reloadMul: number;
  // Multipliers
  damageMul: number;
  fireRateMul: number;
  speedMul: number;
  sprintMul: number;
  dashCdMul: number;
  damageReduction: number;
  // Effects
  pierce: number;
  multishot: number;
  explosive: boolean;
  lifesteal: number;
  critChance: number;
  critChanceBonus: number;
  critMul: number;
  bounce: number;
  executeThreshold: number;
  revives: number;
  invulnPeriodic: number;
  invulnT: number;
  bossDamageMul: number;
  aegis: boolean;
  dashExcalibur: boolean;
  dashFireTrail: boolean;
  dashDamageMul: number;
  fireDoT: boolean;
  slowEnemies: boolean;
  poisonPools: boolean;
  nightVision: boolean;
  pickupMagnet: boolean;
  tracker: boolean;
  frenzy: boolean;
  frenzyKills: number;
  frenzyT: number;
  chaosDamage: boolean;
  sanguePorSangue: boolean;
  explosiveKills: boolean;
  lowHpDamageMul: number;
  hpRegenPerSec: number;
  shieldRegenPerSec: number;
  // Movement / dash
  dashCooldown: number;
  dashTimer: number;
  // Unlocked weapons via cards (3..8).
  unlockedWeapons: number[];
  // Per-weapon derived flags.
  weaponPierce: number;
  weaponExplosive: boolean;
  weaponFireDoT: boolean;
}

export function createInitialPlayer(): PlayerRuntime {
  return {
    hp: 100,
    maxHp: 100,
    shield: 0,
    maxShield: 50,
    currentWeapon: 1,
    weaponId: 'rifle',
    ammo: 30,
    maxAmmo: 30,
    fireRate: 0.09,
    baseDamage: 14,
    reloadTime: 2.0,
    pellets: 1,
    spread: 0.02,
    fireCooldown: 0,
    reloading: false,
    reloadT: 0,
    reloadMul: 1.0,
    damageMul: 1.0,
    fireRateMul: 1.0,
    speedMul: 1.0,
    sprintMul: 1.55,
    dashCdMul: 1.0,
    damageReduction: 0,
    pierce: 0,
    multishot: 0,
    explosive: false,
    lifesteal: 0,
    critChance: 0,
    critChanceBonus: 0,
    critMul: 1.5,
    bounce: 0,
    executeThreshold: 0,
    revives: 0,
    invulnPeriodic: 0,
    invulnT: 0,
    bossDamageMul: 1,
    aegis: false,
    dashExcalibur: false,
    dashFireTrail: false,
    dashDamageMul: 1,
    fireDoT: false,
    slowEnemies: false,
    poisonPools: false,
    nightVision: false,
    pickupMagnet: false,
    tracker: false,
    frenzy: false,
    frenzyKills: 0,
    frenzyT: 0,
    chaosDamage: false,
    sanguePorSangue: false,
    explosiveKills: false,
    lowHpDamageMul: 0,
    hpRegenPerSec: 0,
    shieldRegenPerSec: 0,
    dashCooldown: 0,
    dashTimer: 0,
    unlockedWeapons: [],
    weaponPierce: 0,
    weaponExplosive: false,
    weaponFireDoT: false,
  };
}
